#!/usr/bin/env ruby -w

# Simple and Sinister
# https://www.strongfirst.com/achieve/sinister/
#
# This program involves 100 one-hand swings and 10 get-ups. The 10×10 swings
# must be completed in 5 minutes, followed by 1 minute of rest and 10×1 get-ups
# performed in 10 minutes.

require_relative '../helpers'

ready? countdown: 10

10.times do |n|
  perform "10 #{alternating_side}-handed swings"
  rest 30.seconds
end

say "Rest"
rest 1.minute

10.times do |n|
  perform "#{alternating_side} Turkish get-up"
  rest 1.minute
end
